// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuDk2N4L_z6DNpWeGZb9gEC176yQ1evk',
    appId: '1:1055211949553:web:895de0c7964bccf3be8850',
    messagingSenderId: '1055211949553',
    projectId: 'venue-73ba5',
    authDomain: 'venue-73ba5.firebaseapp.com',
    storageBucket: 'venue-73ba5.firebasestorage.app',
    measurementId: 'G-1GBYY6TPQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACAmC3cqW1vzPffm41_LFhzRjrujvYH5s',
    appId: '1:1055211949553:android:c2b1c20822ff4c96be8850',
    messagingSenderId: '1055211949553',
    projectId: 'venue-73ba5',
    storageBucket: 'venue-73ba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMuGm5-xBWQ1jMUe7nXeY8212S2nohxsk',
    appId: '1:1055211949553:ios:bb6affae69e9cf70be8850',
    messagingSenderId: '1055211949553',
    projectId: 'venue-73ba5',
    storageBucket: 'venue-73ba5.firebasestorage.app',
    iosBundleId: 'com.example.activity',
  );
}
